spring.application.name=authentication

#SERVER
server.port=4000
server.servlet.context-path=/authentication

#SPRING.DATASOURCE
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/authentication
spring.datasource.username=postgres
spring.datasource.password=admin

#EMAIL
spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587
spring.mail.username=rindrarochel2505@gmail.com
spring.mail.password=kds4ZKfrtxb1qY95
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


#USER_EMAIL
user_email=yvanroussel31@gmail.com 

#ACTIVATION_URL
mailing.frontend.activation_url=http://localhost:4200/activate-account

#SPRING.JPA
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.generate-ddl=false
spring.jpa.open-in-view=false

#SECURITY
security.secret.key=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
security.expiration=8640000 
