spring.application.name=authentication

#SERVER
server.port=4000
server.servlet.context-path=/authentication

#SPRING.DATASOURCE
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/authentication
spring.datasource.username=postgres
spring.datasource.password=admin


#SPRING.JPA
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.generate-ddl=false
spring.jpa.open-in-view=false
